version: "3"
services:
  frontend:
    container_name: pepo_frontend
    build: .
    ports:
      - "3000:3000"
    environment:
      SECRET_KEY: your_secret_key
      SESSION_SECRET: aaaaaaaa
      CONFIG: development
      API_URL: http://localhost:5000
    volumes:
      - .:/app # Mount your local directory to /app inside the container
    command: npx nodemon --legacy-watch --watch views --watch public --ext js,pug,json,scss server.js
    networks:
      - pepo-network

networks:
  pepo-network:
    external: true
