version: "3"
services:
  frontend:
    container_name: pepo_frontend
    build: .
    ports:
      - "3000:3000"
    environment:
      SECRET_KEY: ${SECRET_KEY} # Externalize secrets for security
      SESSION_SECRET: ${SESSION_SECRET}
      API_URL: http://pepo_backend:5000 # The backend service URL (should match backend service name in Docker)
      SIGNUP_PASSCODE: ${SIGNUP_PASSCODE} # Replace if using a passcode for production
      NODE_ENV: production # Use 'production' for production environments
      PORT: 3000 # Define the port for the frontend
    volumes:
      - .:/app # Only use this in development for live reloading
    command: npm start
    networks:
      - pepo-network

networks:
  pepo-network:
    external: false # Remove external true unless needed
