services:
  web:
    container_name: pepo_backend
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_URI: mongodb://mongo:27017/gourdstocks
      SECRET_KEY: your_secret_key
      LOG_LEVEL: DEBUG
    depends_on:
      - mongo
    volumes:
      - .:/app  # Optional: Mounts the current directory to the container, useful for development
    networks:
      - pepo-network

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - pepo-network

networks:
  pepo-network:
    external: true

volumes:
  mongo-data:
