version: '3'
services:
  
  # Redis service (message broker for Celery)
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  
  # Celery worker service to process tasks
  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A tasks worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  # Celery beat service for scheduling tasks
  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A tasks beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
